language: perl
perl:
    - "5.22"
    - "5.18"
    - "5.16"
env:
    - TEST_ONLINE=1 TEST_INSTALL=1 TEST_MULTILIB=0
    - TEST_ONLINE=1 TEST_INSTALL=1 TEST_MULTILIB=1
    - TEST_ONLINE=1 TEST_INSTALL=1 TEST_MULTILIB=2
    - TEST_ONLINE=1 TEST_INSTALL=0
    - TEST_ONLINE=0 TEST_INSTALL=1 TEST_MULTILIB=0
    - TEST_ONLINE=0 TEST_INSTALL=1 TEST_MULTILIB=1
    - TEST_ONLINE=0 TEST_INSTALL=1 TEST_MULTILIB=2
    - TEST_ONLINE=0 TEST_INSTALL=0
sudo: required
install:
    - sudo bash t/travis-deps/install.sh
    - cpanm Text::Diff Capture::Tiny Test::Output Devel::Cover
script:
    - bash -c 'PROVE=`which prove`; sudo PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine,+ignore,t/,+ignore,prove,db,/home/travis/build/pink-mist/sbotools/cover_db $PROVE -v t/*.t;'
    - sudo chmod -R a+x cover_db
addons:
    artifacts:
        paths: "./cover_db"
